language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: python generate_EthOn_doc.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  fqdn: ethon.consenys.net
  on:
    branch: master
